redis:
  labels:
    io.rancher.scheduler.affinity:host_label: cloud=aliyun
  restart: always
  tty: true
  image: rancherapps.com:5000/redis
  stdin_open: true
pyapp:
  labels:
    io.rancher.scheduler.affinity:host_label: cloud=aliyun
  restart: always
  tty: true
  image: rancherapps.com:5000/python-redis-demo:b$$BUILD_NUMBER$$
  links:
   - 'redis:'
  stdin_open: true
pyapplb:
  labels:
    io.rancher.scheduler.affinity:host_label: cloud=aliyun
  ports:
   - $$PORT_NUMBER$$:5000
  restart: always
  tty: true
  image: rancher/load-balancer-service
  links:
   - pyapp:pyapp
  stdin_open: true
